language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
env:
  global:
    - PACKAGE="cpuid"
  matrix:
    - OCAML_VERSION=4.01
    - OCAML_VERSION=4.02
    - OCAML_VERSION=4.03
    - OCAML_VERSION=4.04
notifications:
  email: false
